# Generated by Django 5.2 on 2025-05-04 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter a valid 10-digit phone number.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
