# Generated by Django 5.2 on 2025-05-16 06:08

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_vendor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='district', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='services.location', verbose_name='Location'),
        ),
    ]
