# Generated by Django 5.2 on 2025-05-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_lead_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='services.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_locations', to='services.location', verbose_name='Location'),
        ),
    ]
