# Generated by Django 5.2 on 2025-05-16 17:10

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_lead_location_alter_vendor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the district.', unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the location.', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the service.', unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='district', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_locations', to='services.location', verbose_name='Location'),
        ),
    ]
